tap "homebrew/cask"
cask_args appdir: "/Applications"

brew "fish"
brew "ghq"
brew "git"
brew "peco"
brew "scrcpy"
brew "tig"
brew "vim"

cask "android-platform-tools"
cask "appcleaner"
cask "caffeine"
