code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension emilast.logfilehighlighter
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension naumovs.color-highlight
code --install-extension patricklee.vsnotes
code --install-extension shardulm94.trailing-spaces
code --install-extension vscode-icons-team.vscode-icons