tap "homebrew/cask"
cask_args appdir: "/Applications"

brew "git"
brew "ghq"
brew "tig"
brew "jq"
brew "fish"
brew "peco"
brew "colordiff"
brew "vim"
brew "ffmpeg"
brew "scrcpy"
brew "kotlin"
brew "mas"
brew "coreutils"

cask "iterm2"
cask "raycast"
cask "appcleaner"
cask "the-unarchiver"
cask "1password"
cask "dropbox"
cask "google-chrome"
cask "google-japanese-ime"
cask "visual-studio-code"
cask "insomnia"
cask "iina"
cask "yacreader"
cask "transmission"
cask "qfinder-pro"
cask "keepingyouawake"
cask "keyboardcleantool"
cask "onyx"
cask "skype"
cask "daisydisk"

mas "Skitch", id: 425955336
mas "WinArchiver", id: 413215883
mas "Kindle", id: 405399194